[workspace]
authors = ["Wim Smets <wim.smets@cistim.be>"]
channels = ["conda-forge"]
name = "dw-images"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.3,<3.15"
typer = ">=0.24.0,<0.25"
